### ISSUE TITLE
バグが出ました

### ISSUE THREAD

**Issue by IanBrison** [thira3/calculator#1]
小数点の計算で変な誤差が出ました。将来的なメジャーアップデートなどで改善する予定はありますか？

**Comment by thira3** [comment]
そうですね、現在はJavaScriptのeval()を用いて実装をしているため
JavaScriptの仕様上IEEE754という規格だと少数の計算で誤差が出てしまうようです。

今後時間を作って少数の計算の誤差の修正は行う予定です。
